### ISSUE TITLE
Printer produces front-back order only

### ISSUE THREAD

**Issue by Lloydbiker** [mate-desktop/mate-utils#281]
#### Actual behaviour: Selection of 'Reverse' in print menu makes no change. Still produces output (print up) page 1 on bottom, last page on top.
Note: Print menu graphic indicates last on bottom, first on top, print up
#### Exception: Internet '.pdf' and internally stored files  opened with 'LibreOffice' (default set) print in reverse page order, when requested (Uses a different 'Print control' menu)
Note: Published .pdf documents with multiple columns would not display cleanly, using LibreOffice. Switched 'Default' for .pdf to 'Document Viewer', cleaned up display. Back to inoperative 'Reverse' selection, regardless of graphics indication.

**Comment by Lloydbiker** [comment]
Updated to LM 19.3 MATE (Tricia) today, in hopes that might clear the bug. No go, same problem.

**Comment by lukefromdc** [comment]
Reversing print order from Atril, then printing to another PDF (so as not to waste paper and very expensive ink) worked fine for me. In other words I could not reproduce this.

Note that print dialogs are provided by GTK itself (but take data from the calling program), you might have hit an issue with gtk itself that has been resolved in a later version. I have locally compiled GTK 3.24.23 on my system, presumably you have an older version of GTK3 installed.

**Comment by Lloydbiker** [comment]
What version of Mint are you running?
My 'upgrade' from 18.x to 19.3 just carried the fault over, so now, I'm contemplating a 'fresh' install of Mint 19.3 'Tricia', to see if that fixes the fault.
Comments?
Note: The 'LibreOffice' print menu works fine. Selection of 'Reverse' changes display from 1st page to last page, and display changes, as pages are printed. Regular 'Print Menu' just changes menu markers with no results. Can't find any GTK file.

**Comment by Lloydbiker** [comment]
Closed in error.

**Comment by Lloydbiker** [comment]
I did find a reference listed in 'packages installed'   (ibus-gtk	install) while setting up 'backups' for a reinstall of 19.3

**Comment by Lloydbiker** [comment]
Completed re-install of MATE 19.3 'Tricia', but problem still exists.

**Comment by Lloydbiker** [comment]
Further to this: I have discovered that with recent updates to Linux Mint 19.3 'Tricia', the selection of 'File/Print' from browser page, produces a new 'Menu', which has no 'Reverse Print Order' option (But offers 'Systems Dialog' access). A change from 'Color' to 'B-W' changes the display to 'B-W', but the printer output remains 'Color'. Using the 'Systems Dialog' access, I am offered 'Reverse Order Print' and 'Grey-scale'  options, but my printer output is page 1 first, subsequent pages on top, and color, regardless of selections. The print dialog of 'Libre Office' works as expected, no problems.
 Note: Using alternate methods to avoid using paper/ink just hides the problem. Try printing a simple two-page document.
